version: '3.3'
services:
  db:
    image: mariadb:10
    container_name: mariadb
    restart: always
    platform: linux/amd64
    environment:
      MARIADB_DATABASE: 'db'
      MARIADB_USER: 'test'
      MARIADB_PASSWORD: 'travel'
      MARIADB_ROOT_PASSWORD: 'travel'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/Users/jeong/docker-repository
# Names our volume
volumes:
  my-db: